### ISSUE TITLE
Tinyhttp error in types

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/milliparsec#6] opened 2020-12-28 04:54 UTC
I have tried to use json() with tinyhttp but it says `nextfunction | undefined` isnt assignable to `nextfunction`. 

A workaround would be
```typescript
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
app.use([(req, res, next) => bodyParser.json()(req, res, next!), logger()]);
```
Which makes sure next function is defnitely defined, however this isn't the best solution to fixing this.

**Comment by talentlessguy** [comment] 2021-01-08 08:03
What solution would you propose?

**Comment by talentlessguy** [comment] 2021-02-06 18:44
Can't reproduce, so closing

**Closed by talentlessguy** 2021-02-06 18:44 UTC
